import { getDatabase } from './database';
type MixDesignEngineRow = { mixDesignId: string; concreteType: string; targetStrengthMpa: number; requiredSlumpMm: number; maxAggregateSizeMm: number; exposureSummary: string | null; projectName: string; city: string | null; locationDescription: string | null; structureType: string | null; elementType: string | null; clientName: string | null; contractorName: string | null; consultantName: string | null; labName: string | null; labLicenseNumber: string | null; labAddress: string | null; labPhone: string | null; designerName: string | null; designerRole: string | null; designerLicenseNumber: string | null; designerPhone: string | null; designerEmail: string | null; };
type SievePassingRow = { sieveSizeMm: number; percentPassing: number; standardMin?: number | null; standardMax?: number | null; };
type AggregateEngineRow = { id: string; name: string; material_type: string; aggregate_role: string | null; nominal_size_mm: number | null; fractured_face_percent: number | null; specific_gravity: number | null; absorption_percent: number | null; moisture_percent: number | null; unit_weight_kg_m3: number | null; chloride_percent: number | null; astm_c117_finer_75um_percent: number | null; finer_75um_limit_percent: number | null; aggregate_test_evidence_ref: string | null; astm_c29_rodded_unit_weight_kg_m3: number | null; astm_c127_c128_ssd_specific_gravity: number | null; astm_c127_c128_absorption_percent: number | null; aggregate_quality_standard: string | null; la_abrasion_method: string | null; la_abrasion_loss_percent: number | null; la_abrasion_limit_percent: number | null; soundness_salt: string | null; astm_c88_soundness_loss_percent: number | null; soundness_limit_percent: number | null; astm_c142_clay_lumps_percent: number | null; clay_lumps_limit_percent: number | null; astm_c123_lightweight_particles_percent: number | null; lightweight_particles_limit_percent: number | null; advanced_aggregate_evidence_ref: string | null; astm_d4791_flat_elongated_percent: number | null; flat_elongated_limit_percent: number | null; astm_d4791_dimensional_ratio: string | null; astm_d5821_fractured_particles_percent: number | null; fractured_particles_min_percent: number | null; fractured_faces_required: number | null; shape_texture_evidence_ref: string | null; asr_reactivity_class: string | null; asr_qualification_method: string | null; astm_c1260_expansion_14d_percent: number | null; astm_c1293_expansion_1y_percent: number | null; asr_performance_evidence_ref: string | null; source: string | null; fineness_modulus?: number | null; gradation_rows?: Array<{ sieve_size_mm: number; percent_passing: number; standard_min: number | null; standard_max: number | null; }>; };
type CementitiousRow = { id: string; name: string; material_type: string; material_subtype: string | null; specific_gravity: number | null; binder_share_percent: number | null; replacement_percent: number | null; chloride_percent: number | null; alkali_percent: number | null; standard_designation: string | null; source: string | null; manufacturer: string | null; product_code: string | null; sulfate_resistance_class: string | null; sulfate_qualification_method: string | null; astm_c1012_expansion_6m_percent: number | null; astm_c1012_expansion_12m_percent: number | null; sulfate_performance_evidence_ref: string | null; astm_c1567_expansion_14d_percent: number | null; asr_performance_evidence_ref: string | null; };
type BlendEngineRow = { material_id: string; material_name: string; share_percent: number; };
type OptimizerSettingsRow = { enabled: number; stepPercent: number; fineShareMinPercent: number | null; fineShareMaxPercent: number | null; };
type OptimizerConstraintRow = { materialId: string; minPercent: number | null; maxPercent: number | null; };
type CombinedLimitRow = { sieveSizeMm: number; lowerPercent: number | null; upperPercent: number | null; };
type DurabilityEngineRow = { freeze_thaw_exposure: number; freeze_water_exposure: string; soil_water_soluble_sulfate_percent: number | null; water_dissolved_sulfate_ppm: number | null; seawater_exposure: number; water_contact: number; low_permeability_required: number; moisture_exposure: number; external_chloride_exposure: number; reinforced_or_embedded_metal: number; prestressed_concrete: number; };
const FM_SIEVES_MM = [4.75, 2.36, 1.18, 0.6, 0.3, 0.15];
export function buildNormalMixPayload(mixDesignId: string) {
  if (!mixDesignId.trim()) throw new Error('شناسه طرح اختلاط برای محاسبه الزامی است.'); const database = getDatabase();
  const mix = database.prepare(`SELECT md.id AS mixDesignId, md.concrete_type AS concreteType, md.target_strength_mpa AS targetStrengthMpa, md.required_slump_mm AS requiredSlumpMm, md.max_aggregate_size_mm AS maxAggregateSizeMm, md.exposure_summary AS exposureSummary, p.project_name AS projectName, p.city AS city, p.location_description AS locationDescription, p.structure_type AS structureType, p.element_type AS elementType, p.client_name AS clientName, p.contractor_name AS contractorName, p.consultant_name AS consultantName, l.lab_name AS labName, l.license_number AS labLicenseNumber, l.address AS labAddress, l.phone AS labPhone, d.full_name AS designerName, d.role AS designerRole, d.license_or_membership_number AS designerLicenseNumber, d.phone AS designerPhone, d.email AS designerEmail FROM mix_designs md INNER JOIN projects p ON p.id = md.project_id LEFT JOIN laboratories l ON l.id = md.laboratory_id LEFT JOIN designers d ON d.id = md.designer_id WHERE md.id = ?`).get(mixDesignId) as MixDesignEngineRow | undefined;
  if (!mix) throw new Error('طرح اختلاط انتخاب‌شده در دیتابیس پیدا نشد.');
  const aggregates = database.prepare(`SELECT id, name, material_type, aggregate_role, nominal_size_mm, fractured_face_percent, specific_gravity, absorption_percent, moisture_percent, unit_weight_kg_m3, chloride_percent, astm_c117_finer_75um_percent, finer_75um_limit_percent, aggregate_test_evidence_ref, astm_c29_rodded_unit_weight_kg_m3, astm_c127_c128_ssd_specific_gravity, astm_c127_c128_absorption_percent, aggregate_quality_standard, la_abrasion_method, la_abrasion_loss_percent, la_abrasion_limit_percent, soundness_salt, astm_c88_soundness_loss_percent, soundness_limit_percent, astm_c142_clay_lumps_percent, clay_lumps_limit_percent, astm_c123_lightweight_particles_percent, lightweight_particles_limit_percent, advanced_aggregate_evidence_ref, astm_d4791_flat_elongated_percent, flat_elongated_limit_percent, astm_d4791_dimensional_ratio, astm_d5821_fractured_particles_percent, fractured_particles_min_percent, fractured_faces_required, shape_texture_evidence_ref, asr_reactivity_class, asr_qualification_method, astm_c1260_expansion_14d_percent, astm_c1293_expansion_1y_percent, asr_performance_evidence_ref, source FROM materials WHERE mix_design_id = ? AND material_type IN ('fine_aggregate', 'coarse_aggregate') ORDER BY rowid`).all(mixDesignId) as AggregateEngineRow[];
  for (const aggregate of aggregates) { const rows = database.prepare(`SELECT sieve_size_mm AS sieveSizeMm, percent_passing AS percentPassing, standard_min AS standardMin, standard_max AS standardMax FROM aggregate_sieve_results WHERE material_id = ? ORDER BY sieve_size_mm DESC`).all(aggregate.id) as SievePassingRow[]; aggregate.gradation_rows = rows.map(row => ({ sieve_size_mm: row.sieveSizeMm, percent_passing: row.percentPassing, standard_min: row.standardMin ?? null, standard_max: row.standardMax ?? null })); if (aggregate.material_type === 'fine_aggregate') aggregate.fineness_modulus = calculateFinenessModulus(rows); }
  const cementitious = database.prepare(`SELECT id, name, material_type, material_subtype, specific_gravity, binder_share_percent, replacement_percent, chloride_percent, alkali_percent, standard_designation, source, manufacturer, product_code, sulfate_resistance_class, sulfate_qualification_method, astm_c1012_expansion_6m_percent, astm_c1012_expansion_12m_percent, sulfate_performance_evidence_ref, astm_c1567_expansion_14d_percent, asr_performance_evidence_ref FROM materials WHERE mix_design_id = ? AND material_type IN ('cement', 'scm') ORDER BY rowid`).all(mixDesignId) as CementitiousRow[];
  const admixtures = database.prepare(`SELECT id, name, material_type, material_subtype, specific_gravity, density_kg_m3, dosage_value, dosage_unit, solids_percent, chloride_percent, chloride_mg_l, sulfate_mg_l, total_solids_mg_l, alkalis_na2oeq_mg_l, c1602_strength_ratio_7d_percent, c1602_setting_time_deviation_min, c1602_performance_evidence_ref, water_source_class, c1602_last_qualification_date, c1602_last_density_check_date, c1602_density_monitoring_method, c1602_monitoring_evidence_ref, water_share_percent, standard_designation, source, manufacturer, product_code FROM materials WHERE mix_design_id = ? AND material_type IN ('admixture', 'fiber', 'water') ORDER BY rowid`).all(mixDesignId);
  const aggregateBlendShares = database.prepare(`SELECT material_id, material_name, share_percent FROM aggregate_blend_shares WHERE mix_design_id = ? AND share_percent > 0 ORDER BY rowid`).all(mixDesignId) as BlendEngineRow[];
  const manualBlendRow = database.prepare(`SELECT MAX(COALESCE(agc.manual_blend_enabled, 0)) AS manualBlendEnabled FROM materials m LEFT JOIN aggregate_gradation_controls agc ON agc.material_id = m.id WHERE m.mix_design_id = ?`).get(mixDesignId) as { manualBlendEnabled?: number | null } | undefined; const manualBlendEnabled = Boolean(manualBlendRow?.manualBlendEnabled);
  const optimizerSettings = database.prepare(`SELECT enabled, step_percent AS stepPercent, fine_share_min_percent AS fineShareMinPercent, fine_share_max_percent AS fineShareMaxPercent FROM aggregate_blend_optimizer_settings WHERE mix_design_id = ?`).get(mixDesignId) as OptimizerSettingsRow | undefined;
  const optimizerConstraintRows = database.prepare(`SELECT material_id AS materialId, min_percent AS minPercent, max_percent AS maxPercent FROM aggregate_blend_constraints WHERE mix_design_id = ? ORDER BY rowid`).all(mixDesignId) as OptimizerConstraintRow[];
  const combinedLimitRows = database.prepare(`SELECT sieve_size_mm AS sieveSizeMm, lower_percent AS lowerPercent, upper_percent AS upperPercent FROM combined_gradation_limits WHERE mix_design_id = ? ORDER BY sieve_size_mm DESC`).all(mixDesignId) as CombinedLimitRow[];
  const aggregateBlendConstraints = Object.fromEntries(optimizerConstraintRows.map(row => [row.materialId, { min_percent: row.minPercent ?? 0, max_percent: row.maxPercent ?? 100 }]));
  const combinedGradationLimits = combinedLimitRows.filter(row => row.lowerPercent !== null || row.upperPercent !== null).map(row => ({ sieve_size_mm: row.sieveSizeMm, min_percent: row.lowerPercent ?? 0, max_percent: row.upperPercent ?? 100 }));
  const fineAggregateShareRange = optimizerSettings && (optimizerSettings.fineShareMinPercent !== null || optimizerSettings.fineShareMaxPercent !== null) ? [optimizerSettings.fineShareMinPercent ?? 0, optimizerSettings.fineShareMaxPercent ?? 100] : undefined;
  const durability = database.prepare(`SELECT freeze_thaw_exposure, freeze_water_exposure, soil_water_soluble_sulfate_percent, water_dissolved_sulfate_ppm, seawater_exposure, water_contact, low_permeability_required, moisture_exposure, external_chloride_exposure, reinforced_or_embedded_metal, prestressed_concrete FROM durability_inputs WHERE mix_design_id = ?`).get(mixDesignId) as DurabilityEngineRow | undefined;
  const durabilityConditions = durability ? { freeze_thaw_exposure: Boolean(durability.freeze_thaw_exposure), freeze_water_exposure: durability.freeze_water_exposure, soil_water_soluble_sulfate_percent: durability.soil_water_soluble_sulfate_percent, water_dissolved_sulfate_ppm: durability.water_dissolved_sulfate_ppm, seawater_exposure: Boolean(durability.seawater_exposure), water_contact: Boolean(durability.water_contact), low_permeability_required: Boolean(durability.low_permeability_required), moisture_exposure: Boolean(durability.moisture_exposure), external_chloride_exposure: Boolean(durability.external_chloride_exposure), reinforced_or_embedded_metal: Boolean(durability.reinforced_or_embedded_metal), prestressed_concrete: Boolean(durability.prestressed_concrete) } : {};
  return { project: { name: mix.projectName, city: mix.city, location_description: mix.locationDescription, structure_type: mix.structureType, element_type: mix.elementType, client_name: mix.clientName, contractor_name: mix.contractorName, consultant_name: mix.consultantName }, lab: { name: mix.labName, license_number: mix.labLicenseNumber, address: mix.labAddress, phone: mix.labPhone }, designer: { full_name: mix.designerName, role: mix.designerRole, license_or_membership_number: mix.designerLicenseNumber, phone: mix.designerPhone, email: mix.designerEmail }, concrete_type: mix.concreteType, standards: ['ACI_PRC_211_1_22', 'ACI_CODE_318_25', 'ACI_301', 'ASTM_C150', 'ASTM_C595', 'ASTM_C1157', 'ASTM_C618', 'ASTM_C989', 'ASTM_C1240', 'ASTM_C1012', 'ASTM_C1260', 'ASTM_C1293', 'ASTM_C1567', 'ASTM_C1778', 'ASTM_C494', 'ASTM_C260', 'ASTM_C1602', 'ASTM_C1603', 'ASTM_C1218', 'ASTM_C29', 'ASTM_C33', 'ASTM_C117', 'ASTM_C127', 'ASTM_C128', 'ASTM_C136', 'ASTM_C131', 'ASTM_C535', 'ASTM_C88', 'ASTM_C142', 'ASTM_C123', 'ASTM_D4791', 'ASTM_D5821'], materials: { aggregates, aggregate_blend_shares: aggregateBlendShares, cementitious, admixtures }, exposure: { summary: mix.exposureSummary }, durability_conditions: durabilityConditions, requirements: { target_strength_mpa: mix.targetStrengthMpa, slump_mm: mix.requiredSlumpMm, max_aggregate_size_mm: mix.maxAggregateSizeMm }, calculation_options: { source: 'sqlite_saved_mix_design', mix_design_id: mix.mixDesignId, manual_blend_enabled: manualBlendEnabled, aggregate_proportioning_mode: manualBlendEnabled ? 'manual_absolute_volume' : 'aci_coarse_volume', ...(optimizerSettings ? { blend_optimizer_enabled: Boolean(optimizerSettings.enabled), aggregate_blend_optimizer_step_percent: optimizerSettings.stepPercent, aggregate_blend_constraints: aggregateBlendConstraints, combined_gradation_limits: combinedGradationLimits, fine_aggregate_share_range: fineAggregateShareRange } : {}) } };
}
function calculateFinenessModulus(rows: SievePassingRow[]): number | null { const passingBySieve = new Map<number, number>(); for (const row of rows) passingBySieve.set(roundSieve(row.sieveSizeMm), row.percentPassing); let cumulativeRetainedSum = 0; for (const sieve of FM_SIEVES_MM) { const passing = passingBySieve.get(roundSieve(sieve)); if (passing === undefined || !Number.isFinite(passing)) return null; cumulativeRetainedSum += 100 - passing; } return Math.round((cumulativeRetainedSum / 100) * 1000) / 1000; }
function roundSieve(value: number): number { return Math.round(value * 1000) / 1000; }