import { useEffect, useMemo, useState } from 'react';
import { EngineeringDecisionSummaryPanel } from './EngineeringDecisionSummaryPanel';
import { ProductionQcPanel } from './ProductionQcPanel';
import { ReportCenterView } from './ReportCenterView';

type CostRole = 'cementitious' | 'water' | 'fine_aggregate' | 'coarse_aggregate';
type CostInputSet = { id: string; mixDesignId: string; revisionNumber: number; currency: string; sourceReference?: string | null; effectiveAt: string; createdBy?: string | null; createdAt: string; };
type CostLine = { role: CostRole; quantityKgM3: number | null; unitCostPerKg: number | null; lineCostPerM3: number | null; comparable: boolean; };
type RevisionCost = { methodVersion: string; mixDesignId: string; revisionNumber: number; designSource: string; designSnapshotId?: string | null; inputSet: CostInputSet; currency: string; lines: CostLine[]; totalCostPerM3: number; complete: boolean; missingCostRoles: CostRole[]; missingQuantityRoles: CostRole[]; assumptions: string[]; };
type RevisionRow = { revisionNumber?: number; revision_number?: number; };
type CostForm = Record<CostRole, string> & { currency: string; sourceReference: string; effectiveAt: string; };
const roles: CostRole[] = ['cementitious', 'water', 'fine_aggregate', 'coarse_aggregate'];
const roleLabel: Record<CostRole, string> = { cementitious: 'مواد سیمانی', water: 'آب', fine_aggregate: 'سنگدانه ریز', coarse_aggregate: 'سنگدانه درشت' };
const initialForm = (): CostForm => ({ cementitious: '', water: '', fine_aggregate: '', coarse_aggregate: '', currency: 'IRR', sourceReference: '', effectiveAt: new Date().toISOString().slice(0, 10) });
const fmt = (value: number | null | undefined) => value == null ? '—' : new Intl.NumberFormat('fa-IR', { maximumFractionDigits: 3 }).format(value);

export function CostEnginePanel(props: { mixDesignId: string | null }) {
  const [revisions, setRevisions] = useState<number[]>([]); const [selectedRevision, setSelectedRevision] = useState<number | null>(null); const [compareRevision, setCompareRevision] = useState<number | null>(null); const [inputSets, setInputSets] = useState<CostInputSet[]>([]); const [selectedInputSetId, setSelectedInputSetId] = useState(''); const [result, setResult] = useState<RevisionCost | null>(null); const [comparison, setComparison] = useState<RevisionCost | null>(null); const [form, setForm] = useState<CostForm>(initialForm); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { void loadRevisions(); }, [props.mixDesignId]); useEffect(() => { if (selectedRevision != null) void loadInputSets(selectedRevision); }, [props.mixDesignId, selectedRevision]);
  async function loadRevisions() { setResult(null); setComparison(null); setInputSets([]); setSelectedInputSetId(''); setError(''); setMessage(''); if (!props.mixDesignId) { setRevisions([]); setSelectedRevision(null); setCompareRevision(null); return; } try { const response = await window.tolouMixDesigns?.listRevisions(props.mixDesignId) as { status?: string; revisions?: RevisionRow[]; error?: string } | undefined; if (!response || response.status !== 'pass') throw new Error(response?.error ?? 'خواندن Revisionها ناموفق بود.'); const values = (response.revisions ?? []).map(item => Number(item.revisionNumber ?? item.revision_number)).filter(Number.isInteger).sort((a, b) => b - a); setRevisions(values); setSelectedRevision(values[0] ?? null); setCompareRevision(values[1] ?? null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'خطا در خواندن Revisionها'); } }
  async function loadInputSets(revision: number) { if (!props.mixDesignId) return; try { const response = await window.tolouCostEngine?.listInputSets(props.mixDesignId, revision) as { status?: string; inputSets?: CostInputSet[]; error?: string } | undefined; if (!response || response.status !== 'pass') throw new Error(response?.error ?? 'خواندن Cost Input Setها ناموفق بود.'); const sets = response.inputSets ?? []; setInputSets(sets); setSelectedInputSetId(sets[0]?.id ?? ''); } catch (reason) { setInputSets([]); setSelectedInputSetId(''); setError(reason instanceof Error ? reason.message : 'خطا در خواندن Cost Input Setها'); } }
  async function saveInputSet() { if (!props.mixDesignId) return; const items = roles.filter(role => form[role].trim()).map(role => ({ role, unitCostPerKg: Number(form[role]) })); if (!form.currency.trim() || items.length === 0 || items.some(item => !Number.isFinite(item.unitCostPerKg) || item.unitCostPerKg < 0)) { setError('Currency و حداقل یک قیمت معتبر و نامنفی الزامی است.'); return; } setBusy(true); setError(''); setMessage(''); try { const response = await window.tolouCostEngine?.saveInputSet({ mixDesignId: props.mixDesignId, currency: form.currency, sourceReference: form.sourceReference.trim() || null, effectiveAt: form.effectiveAt, items }) as { status?: string; inputSetId?: string; revisionNumber?: number; error?: string } | undefined; if (!response || response.status !== 'pass' || !response.inputSetId) throw new Error(response?.error ?? 'ثبت Cost Input Set ناموفق بود.'); setMessage(`Cost Input Set برای Revision ${response.revisionNumber} ثبت شد.`); setForm(initialForm()); if (response.revisionNumber != null) { setSelectedRevision(response.revisionNumber); await loadInputSets(response.revisionNumber); } } catch (reason) { setError(reason instanceof Error ? reason.message : 'خطا در ثبت Cost Input Set'); } finally { setBusy(false); } }
  async function calculate() { if (!props.mixDesignId || selectedRevision == null) return; setBusy(true); setError(''); setMessage(''); setComparison(null); try { const raw = await window.tolouCostEngine?.calculateRevision(props.mixDesignId, selectedRevision, selectedInputSetId || undefined) as ({ status?: string; error?: string } & Partial<RevisionCost>) | undefined; if (!raw || raw.status !== 'pass') throw new Error(raw?.error ?? 'محاسبه هزینه Revision ناموفق بود.'); setResult(raw as RevisionCost); if (compareRevision != null && compareRevision !== selectedRevision) { const other = await window.tolouCostEngine?.calculateRevision(props.mixDesignId, compareRevision) as ({ status?: string; error?: string } & Partial<RevisionCost>) | undefined; if (other?.status === 'pass') setComparison(other as RevisionCost); else setMessage(`Revision ${selectedRevision} محاسبه شد؛ Revision مقایسه Cost Input Set قابل استفاده ندارد.`); } } catch (reason) { setResult(null); setError(reason instanceof Error ? reason.message : 'خطا در محاسبه هزینه'); } finally { setBusy(false); } }
  const delta = useMemo(() => result && comparison && result.currency === comparison.currency ? result.totalCostPerM3 - comparison.totalCostPerM3 : null, [result, comparison]);
  return <>
    <section className="titlebar"><div><h2>Cost Engine</h2><p>هزینه ردیابی‌پذیر هر m³، قفل‌شده به Revision و Cost Input Set</p></div><div className="toolbar"><button className="btn primary" disabled={busy || selectedRevision == null || !selectedInputSetId} onClick={() => void calculate()}>{busy ? 'در حال پردازش...' : 'محاسبه هزینه'}</button></div></section>
    {error && <div className="alert danger">{error}</div>}{message && <div className="alert info">{message}</div>}{!props.mixDesignId && <div className="alert warn">ابتدا یک Mix Design فعال را انتخاب کنید.</div>}
    {props.mixDesignId && <section className="content-grid">
      <article className="panel"><div className="panel-head"><div><h3>Cost Input Set</h3><span>Immutable commercial inputs</span></div></div><div className="panel-body form-body"><label className="field"><span>Currency</span><input value={form.currency} onChange={event => setForm(previous => ({ ...previous, currency: event.target.value }))} /></label><label className="field"><span>Effective date</span><input type="date" value={form.effectiveAt} onChange={event => setForm(previous => ({ ...previous, effectiveAt: event.target.value }))} /></label>{roles.map(role => <label className="field" key={role}><span>{roleLabel[role]} — cost/kg</span><input type="number" min="0" step="any" value={form[role]} onChange={event => setForm(previous => ({ ...previous, [role]: event.target.value }))} /></label>)}<label className="field"><span>Source / invoice / quotation reference</span><input value={form.sourceReference} onChange={event => setForm(previous => ({ ...previous, sourceReference: event.target.value }))} /></label><button className="btn success" disabled={busy} onClick={() => void saveInputSet()}>ثبت Cost Input Set جدید</button><div className="alert warn">ثبت قیمت فقط برای Revision جاری انجام می‌شود و رکوردهای قبلی تغییر نمی‌کنند.</div></div></article>
      <article className="panel wide-panel"><div className="panel-head"><div><h3>Revision Cost Analysis</h3><span>Deterministic · traceable · no standards inference</span></div></div><div className="panel-body form-body"><label className="field"><span>Revision</span><select value={selectedRevision ?? ''} onChange={event => setSelectedRevision(Number(event.target.value))}>{revisions.map(value => <option value={value} key={value}>Revision {value}</option>)}</select></label><label className="field"><span>Cost Input Set</span><select value={selectedInputSetId} onChange={event => setSelectedInputSetId(event.target.value)}><option value="">انتخاب کنید</option>{inputSets.map(set => <option value={set.id} key={set.id}>{set.currency} · {new Date(set.effectiveAt).toLocaleDateString('fa-IR')} · {set.sourceReference || 'بدون مرجع'}</option>)}</select></label><label className="field"><span>Compare with Revision</span><select value={compareRevision ?? ''} onChange={event => setCompareRevision(event.target.value ? Number(event.target.value) : null)}><option value="">بدون مقایسه</option>{revisions.filter(value => value !== selectedRevision).map(value => <option value={value} key={value}>Revision {value}</option>)}</select></label>{inputSets.length === 0 && <div className="alert warn">برای Revision انتخاب‌شده Cost Input Set ثبت نشده است.</div>}</div></article>
    </section>}
    {result && <section className="panel form-panel"><div className="panel-head"><div><h3>Cost Breakdown — Revision {result.revisionNumber}</h3><span>{result.methodVersion} · {result.designSource}</span></div><span className={`badge ${result.complete ? 'green' : 'orange'}`}>{result.complete ? 'Complete' : 'Partial'}</span></div><div className="panel-body"><p><b>Total:</b> {fmt(result.totalCostPerM3)} {result.currency}/m³</p><p><b>Input source:</b> {result.inputSet.sourceReference || '—'} · <b>Effective:</b> {new Date(result.inputSet.effectiveAt).toLocaleDateString('fa-IR')}</p><div className="table-wrap"><table><thead><tr><th>Role</th><th>Quantity kg/m³</th><th>Unit cost/kg</th><th>Line cost/m³</th><th>Coverage</th></tr></thead><tbody>{result.lines.map(line => <tr key={line.role}><td>{roleLabel[line.role]}</td><td>{fmt(line.quantityKgM3)}</td><td>{fmt(line.unitCostPerKg)}</td><td>{fmt(line.lineCostPerM3)}</td><td>{line.comparable ? 'Available' : 'Missing'}</td></tr>)}</tbody></table></div>{!result.complete && <div className="alert warn">این Total ناقص است. Missing cost: {result.missingCostRoles.map(role => roleLabel[role]).join('، ') || '—'} | Missing quantity: {result.missingQuantityRoles.map(role => roleLabel[role]).join('، ') || '—'}</div>}{comparison && <div className="alert info"><b>Revision comparison:</b> R{result.revisionNumber} = {fmt(result.totalCostPerM3)} {result.currency}/m³ · R{comparison.revisionNumber} = {fmt(comparison.totalCostPerM3)} {comparison.currency}/m³ {delta != null ? `· Δ = ${fmt(delta)} ${result.currency}/m³` : '· Currency mismatch: Δ محاسبه نشد.'}</div>}<div className="alert warn">Cost v1 فقط Cementitious، Water، Fine Aggregate و Coarse Aggregate را از summary quantities محاسبه می‌کند؛ Cement/SCM/Admixture/Fiber split استنتاج نمی‌شود. هیچ acceptance/pass-fail استانداردی اعمال نشده است.</div></div></section>}
    <EngineeringDecisionSummaryPanel mixDesignId={props.mixDesignId} />
    <ProductionQcPanel mixDesignId={props.mixDesignId} />
    <ReportCenterView mixDesignId={props.mixDesignId} />
  </>;
}
