import { useState } from 'react';
import type { AggregateRole, MaterialInput, MaterialRecord, MaterialSubtype, MaterialType, MoistureCondition, SaveMaterialResponse, SulfateQualificationMethod, SulfateResistanceClass } from './types/material';

const materialTypes: Array<{ value: MaterialType; label: string }> = [
  { value: 'cement', label: 'سیمان' }, { value: 'water', label: 'آب' }, { value: 'fine_aggregate', label: 'سنگدانه ریز / ماسه' }, { value: 'coarse_aggregate', label: 'سنگدانه درشت / شن' }, { value: 'scm', label: 'مواد مکمل سیمانی' }, { value: 'admixture', label: 'افزودنی شیمیایی' }, { value: 'fiber', label: 'الیاف' }
];
const aggregateRoles: Array<{ value: AggregateRole; label: string; materialType: 'fine_aggregate' | 'coarse_aggregate' | 'both' }> = [
  { value: 'natural_sand', label: 'ماسه طبیعی', materialType: 'fine_aggregate' }, { value: 'manufactured_sand', label: 'ماسه شکسته', materialType: 'fine_aggregate' }, { value: 'correction_aggregate', label: 'سنگدانه اصلاحی', materialType: 'both' }, { value: 'pea_gravel', label: 'نخودی', materialType: 'coarse_aggregate' }, { value: 'coarse_gravel', label: 'بادامی', materialType: 'coarse_aggregate' }, { value: 'coarse_12_5', label: 'شن 12.5 میلی‌متر', materialType: 'coarse_aggregate' }, { value: 'coarse_19', label: 'شن 19 میلی‌متر', materialType: 'coarse_aggregate' }, { value: 'coarse_25', label: 'شن 25 میلی‌متر', materialType: 'coarse_aggregate' }, { value: 'recycled_aggregate', label: 'سنگدانه بازیافتی', materialType: 'both' }, { value: 'lightweight_aggregate', label: 'سنگدانه سبک', materialType: 'both' }, { value: 'heavyweight_aggregate', label: 'سنگدانه سنگین', materialType: 'both' }, { value: 'custom', label: 'نام/نقش سفارشی', materialType: 'both' }
];
const moistureConditions: Array<{ value: MoistureCondition; label: string }> = [
  { value: 'oven_dry', label: 'خشک آون' }, { value: 'air_dry', label: 'خشک هوایی' }, { value: 'ssd', label: 'SSD' }, { value: 'wet', label: 'مرطوب' }, { value: 'stockpile', label: 'وضعیت دپو' }
];
const sulfateClasses: Array<{ value: SulfateResistanceClass; label: string }> = [
  { value: 'none', label: 'اعلام نشده / بدون کلاس' }, { value: 'MS', label: 'MS - مقاومت متوسط' }, { value: 'HS', label: 'HS - مقاومت بالا' }, { value: 'qualified_combination', label: 'ترکیب واجد Qualification' }
];
const sulfateMethods: Array<{ value: SulfateQualificationMethod; label: string }> = [
  { value: 'product_designation', label: 'Designation مستقیم محصول' }, { value: 'astm_c1012', label: 'ASTM C1012/C1012M' }, { value: 'documented_service_record', label: 'سابقه عملکرد مستند' }, { value: 'engineer_approved_combination', label: 'ترکیب تأییدشده توسط مهندس' }
];
const subtypes: Array<{ value: MaterialSubtype; label: string; types: MaterialType[] }> = [
  { value: 'portland_cement', label: 'سیمان پرتلند', types: ['cement'] }, { value: 'blended_cement', label: 'سیمان آمیخته', types: ['cement'] },
  { value: 'slag_cement', label: 'سرباره آسیاب‌شده', types: ['scm'] }, { value: 'fly_ash', label: 'خاکستر بادی', types: ['scm'] }, { value: 'silica_fume', label: 'میکروسیلیس', types: ['scm'] }, { value: 'natural_pozzolan', label: 'پوزولان طبیعی', types: ['scm'] }, { value: 'calcined_clay', label: 'رس کلسینه', types: ['scm'] }, { value: 'limestone_filler', label: 'فیلر آهکی', types: ['scm'] }, { value: 'other_scm', label: 'SCM دیگر', types: ['scm'] },
  { value: 'water_reducer', label: 'کاهنده آب', types: ['admixture'] }, { value: 'high_range_water_reducer', label: 'فوق‌روان‌کننده', types: ['admixture'] }, { value: 'retarder', label: 'دیرگیرکننده', types: ['admixture'] }, { value: 'accelerator', label: 'زودگیرکننده بدون CaCl₂', types: ['admixture'] }, { value: 'calcium_chloride_accelerator', label: 'زودگیرکننده بر پایه CaCl₂', types: ['admixture'] }, { value: 'air_entrainer', label: 'هوازا', types: ['admixture'] }, { value: 'viscosity_modifier', label: 'اصلاح‌کننده ویسکوزیته', types: ['admixture'] }, { value: 'corrosion_inhibitor', label: 'بازدارنده خوردگی', types: ['admixture'] }, { value: 'shrinkage_reducer', label: 'کاهنده جمع‌شدگی', types: ['admixture'] }, { value: 'other_admixture', label: 'افزودنی دیگر', types: ['admixture'] },
  { value: 'steel_fiber', label: 'الیاف فولادی', types: ['fiber'] }, { value: 'polypropylene_fiber', label: 'الیاف پلی‌پروپیلن', types: ['fiber'] }, { value: 'glass_fiber', label: 'الیاف شیشه', types: ['fiber'] }, { value: 'basalt_fiber', label: 'الیاف بازالت', types: ['fiber'] }, { value: 'other_fiber', label: 'الیاف دیگر', types: ['fiber'] },
  { value: 'mixing_water', label: 'آب اختلاط', types: ['water'] }, { value: 'wash_water', label: 'آب بازیافتی/شستشو', types: ['water'] }, { value: 'other', label: 'سایر', types: ['water'] }
];

const initialMaterial: Omit<MaterialInput, 'mixDesignId'> = {
  materialType: 'fine_aggregate', aggregateRole: 'natural_sand', nominalSizeMm: 4.75, fracturedFacePercent: null, moistureCondition: 'stockpile', name: 'ماسه طبیعی 0-6 منبع نمونه', source: 'یزد', specificGravity: 2.65, absorptionPercent: 1.8, moisturePercent: 3.2, unitWeightKgM3: 1650, notes: 'نتایج آزمایشگاهی معتبر ثبت شود.',
  materialSubtype: null, standardDesignation: null, densityKgM3: null, dosageValue: null, dosageUnit: null, binderSharePercent: null, replacementPercent: null, solidsPercent: null, chloridePercent: null, chlorideMgL: null, waterSharePercent: null, alkaliPercent: null, lossOnIgnitionPercent: null, activityIndexPercent: null, manufacturer: null, productCode: null,
  sulfateResistanceClass: null, sulfateQualificationMethod: null, astmC1012Expansion6mPercent: null, astmC1012Expansion12mPercent: null, sulfatePerformanceEvidenceRef: null
};

export function MaterialsView(props: { mixDesignId: string | null }) {
  const [material, setMaterial] = useState(initialMaterial); const [materials, setMaterials] = useState<MaterialRecord[]>([]); const [status, setStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle'); const [message, setMessage] = useState('');
  const isAggregate = material.materialType === 'fine_aggregate' || material.materialType === 'coarse_aggregate';
  const isBinder = material.materialType === 'cement' || material.materialType === 'scm';
  const isAdmixture = material.materialType === 'admixture'; const isFiber = material.materialType === 'fiber'; const isWater = material.materialType === 'water';
  const visibleRoles = aggregateRoles.filter(role => role.materialType === 'both' || role.materialType === material.materialType);
  const visibleSubtypes = subtypes.filter(item => item.types.includes(material.materialType));

  async function saveMaterial() {
    setStatus('saving'); setMessage('');
    try { if (!props.mixDesignId) throw new Error('ابتدا یک پروژه/طرح جدید ذخیره کنید.'); if (!window.tolouMaterials) throw new Error('API مصالح در دسترس نیست.'); const result = await window.tolouMaterials.save({ ...material, mixDesignId: props.mixDesignId } as MaterialInput) as SaveMaterialResponse; if (result.status !== 'pass') throw new Error(result.error ?? 'ذخیره مصالح ناموفق بود.'); const list = await window.tolouMaterials.listByMixDesign(props.mixDesignId) as { status: string; materials?: MaterialRecord[] }; setMaterials(list.materials ?? []); setStatus('saved'); setMessage('مصالح با موفقیت به طرح فعلی اضافه شد.'); } catch (error) { setStatus('error'); setMessage(error instanceof Error ? error.message : 'خطای ناشناخته در ذخیره مصالح'); }
  }
  function setValue(key: keyof typeof material, value: string | number | null) { setMaterial(previous => ({ ...previous, [key]: value })); }
  function changeType(type: MaterialType) {
    const defaultSubtype = subtypes.find(item => item.types.includes(type))?.value ?? null;
    setMaterial(previous => ({ ...previous, materialType: type, aggregateRole: type === 'fine_aggregate' ? 'natural_sand' : type === 'coarse_aggregate' ? 'coarse_gravel' : null, materialSubtype: defaultSubtype, binderSharePercent: type === 'cement' ? 100 : null, waterSharePercent: type === 'water' ? 100 : null, specificGravity: type === 'cement' ? 3.15 : type === 'scm' ? 2.4 : previous.specificGravity, sulfateResistanceClass: type === 'cement' || type === 'scm' ? previous.sulfateResistanceClass : null, sulfateQualificationMethod: type === 'cement' || type === 'scm' ? previous.sulfateQualificationMethod : null }));
  }
  function useAggregatePreset(kind: 'sand' | 'pea' | 'coarse') { if (kind === 'sand') setMaterial(previous => ({ ...previous, materialType: 'fine_aggregate', aggregateRole: 'natural_sand', nominalSizeMm: 4.75, name: 'ماسه طبیعی 0-6' })); else if (kind === 'pea') setMaterial(previous => ({ ...previous, materialType: 'coarse_aggregate', aggregateRole: 'pea_gravel', nominalSizeMm: 12.5, name: 'شن نخودی' })); else setMaterial(previous => ({ ...previous, materialType: 'coarse_aggregate', aggregateRole: 'coarse_gravel', nominalSizeMm: 19, name: 'شن بادامی' })); }
  function countByType(type: MaterialType) { return materials.filter(item => item.materialType === type).length; }

  return <><section className="titlebar"><div><h2>مصالح و منابع طرح اختلاط</h2><p>بانک کامل سنگدانه، سیمان، SCM، آب، افزودنی و الیاف با ردیابی محصول و منبع</p></div><div className="toolbar"><button className="btn success" disabled={status === 'saving'} onClick={saveMaterial}>{status === 'saving' ? 'در حال ذخیره...' : 'ذخیره مصالح'}</button></div></section>
    {!props.mixDesignId && <div className="alert warn">برای ثبت مصالح، ابتدا از بخش «پروژه جدید» یک طرح را ذخیره کنید.</div>}{message && <div className={`alert ${status === 'error' ? 'danger' : 'ok'}`}>{message}</div>}
    <section className="content-grid"><article className="panel wide-panel"><div className="panel-head"><div><h3>فرم مهندسی مصالح</h3><span>فیلدها متناسب با نوع ماده تغییر می‌کنند</span></div><span className="badge blue">Material System</span></div><div className="panel-body form-body">
      <div className="quick-actions full"><button className="btn ghost" onClick={() => useAggregatePreset('sand')}>ماسه</button><button className="btn ghost" onClick={() => useAggregatePreset('pea')}>نخودی</button><button className="btn ghost" onClick={() => useAggregatePreset('coarse')}>بادامی</button></div>
      <label className="field"><span>نوع مصالح</span><select value={material.materialType} onChange={event => changeType(event.target.value as MaterialType)}>{materialTypes.map(type => <option value={type.value} key={type.value}>{type.label}</option>)}</select></label>
      {isAggregate && <label className="field"><span>نقش سنگدانه</span><select value={material.aggregateRole ?? 'custom'} onChange={event => setValue('aggregateRole', event.target.value as AggregateRole)}>{visibleRoles.map(role => <option value={role.value} key={role.value}>{role.label}</option>)}</select></label>}
      {!isAggregate && <label className="field"><span>زیرنوع ماده</span><select value={material.materialSubtype ?? visibleSubtypes[0]?.value ?? 'other'} onChange={event => setValue('materialSubtype', event.target.value as MaterialSubtype)}>{visibleSubtypes.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label>}
      <Field label="نام مصالح / محصول" value={material.name} onChange={value => setValue('name', value)} /><Field label="منبع / کارخانه" value={material.source} onChange={value => setValue('source', value)} />
      {!isAggregate && <Field label="سازنده" value={material.manufacturer ?? ''} onChange={value => setValue('manufacturer', value)} />}{!isAggregate && <Field label="کد محصول" value={material.productCode ?? ''} onChange={value => setValue('productCode', value)} />}{!isAggregate && <Field label="استاندارد / Designation" value={material.standardDesignation ?? ''} onChange={value => setValue('standardDesignation', value)} />}
      {isAggregate && <NumberField label="اندازه اسمی mm" value={material.nominalSizeMm} onChange={value => setValue('nominalSizeMm', value)} />}{isAggregate && <NumberField label="درصد شکستگی %" value={material.fracturedFacePercent} onChange={value => setValue('fracturedFacePercent', value)} />}{isAggregate && <label className="field"><span>وضعیت رطوبتی</span><select value={material.moistureCondition ?? 'stockpile'} onChange={event => setValue('moistureCondition', event.target.value as MoistureCondition)}>{moistureConditions.map(condition => <option value={condition.value} key={condition.value}>{condition.label}</option>)}</select></label>}
      {(isAggregate || isBinder) && <NumberField label="وزن مخصوص" value={material.specificGravity} onChange={value => setValue('specificGravity', value)} />}{isAggregate && <NumberField label="جذب آب %" value={material.absorptionPercent} onChange={value => setValue('absorptionPercent', value)} />}{isAggregate && <NumberField label="رطوبت فعلی %" value={material.moisturePercent} onChange={value => setValue('moisturePercent', value)} />}{isAggregate && <NumberField label="وزن واحد kg/m³" value={material.unitWeightKgM3} onChange={value => setValue('unitWeightKgM3', value)} />}
      {isBinder && <NumberField label="سهم از کل مواد سیمانی %" value={material.binderSharePercent ?? null} onChange={value => setValue('binderSharePercent', value)} />}{material.materialType === 'scm' && <NumberField label="درصد جایگزینی %" value={material.replacementPercent ?? null} onChange={value => setValue('replacementPercent', value)} />}{material.materialType === 'scm' && <NumberField label="Activity Index %" value={material.activityIndexPercent ?? null} onChange={value => setValue('activityIndexPercent', value)} />}{material.materialType === 'scm' && <NumberField label="LOI %" value={material.lossOnIgnitionPercent ?? null} onChange={value => setValue('lossOnIgnitionPercent', value)} />}
      {isBinder && <label className="field"><span>کلاس مقاومت سولفاتی</span><select value={material.sulfateResistanceClass ?? 'none'} onChange={event => setValue('sulfateResistanceClass', event.target.value as SulfateResistanceClass)}>{sulfateClasses.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label>}
      {isBinder && <label className="field"><span>روش Qualification سولفاتی</span><select value={material.sulfateQualificationMethod ?? 'product_designation'} onChange={event => setValue('sulfateQualificationMethod', event.target.value as SulfateQualificationMethod)}>{sulfateMethods.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label>}
      {isBinder && material.sulfateQualificationMethod === 'astm_c1012' && <NumberField label="ASTM C1012 انبساط 6 ماه %" value={material.astmC1012Expansion6mPercent ?? null} onChange={value => setValue('astmC1012Expansion6mPercent', value)} />}{isBinder && material.sulfateQualificationMethod === 'astm_c1012' && <NumberField label="ASTM C1012 انبساط 12 ماه %" value={material.astmC1012Expansion12mPercent ?? null} onChange={value => setValue('astmC1012Expansion12mPercent', value)} />}{isBinder && <Field label="مرجع مدرک عملکرد / گزارش آزمایش" value={material.sulfatePerformanceEvidenceRef ?? ''} onChange={value => setValue('sulfatePerformanceEvidenceRef', value)} />}
      {(isAggregate || isBinder || isAdmixture) && <NumberField label="کلراید ماده % جرمی" value={material.chloridePercent ?? null} onChange={value => setValue('chloridePercent', value)} />}
      {(isAdmixture || isFiber) && <NumberField label="دوز مصرف" value={material.dosageValue ?? null} onChange={value => setValue('dosageValue', value)} />}{(isAdmixture || isFiber) && <Field label="واحد دوز (مثلاً kg/m³ یا %binder)" value={material.dosageUnit ?? ''} onChange={value => setValue('dosageUnit', value)} />}{isAdmixture && <NumberField label="درصد مواد جامد %" value={material.solidsPercent ?? null} onChange={value => setValue('solidsPercent', value)} />}{(isAdmixture || isWater) && <NumberField label="چگالی kg/m³" value={material.densityKgM3 ?? null} onChange={value => setValue('densityKgM3', value)} />}
      {isWater && <NumberField label="کلراید آب mg/L" value={material.chlorideMgL ?? null} onChange={value => setValue('chlorideMgL', value)} />}{isWater && <NumberField label="سهم این منبع آب %" value={material.waterSharePercent ?? null} onChange={value => setValue('waterSharePercent', value)} />}
      {material.materialSubtype === 'calcium_chloride_accelerator' && <div className="alert danger full">این محصول به‌صورت CaCl₂ معرفی شده است؛ موتور در S2/S3 و بتن پیش‌تنیده آن را رد خواهد کرد.</div>}
      <label className="field full"><span>یادداشت فنی</span><textarea value={material.notes} onChange={event => setValue('notes', event.target.value)} /></label>
    </div></article>
    <article className="panel wide-panel"><div className="panel-head"><div><h3>مصالح ثبت‌شده</h3><span>ماسه {countByType('fine_aggregate')} | شن {countByType('coarse_aggregate')} | سیمان {countByType('cement')} | SCM {countByType('scm')} | افزودنی {countByType('admixture')} | آب {countByType('water')}</span></div></div><div className="panel-body tablewrap"><table><thead><tr><th>نوع</th><th>نام</th><th>زیرنوع/نقش</th><th>منبع</th><th>SG</th><th>سهم Binder/آب</th><th>کلراید</th><th>سولفات</th><th>استاندارد</th></tr></thead><tbody>{materials.length === 0 && <tr><td colSpan={9}>هنوز مصالحی ثبت نشده است.</td></tr>}{materials.map(item => <tr key={item.id}><td>{materialTypes.find(type => type.value === item.materialType)?.label ?? item.materialType}</td><td>{item.name}</td><td>{aggregateRoles.find(role => role.value === item.aggregateRole)?.label ?? subtypes.find(sub => sub.value === item.materialSubtype)?.label ?? '-'}</td><td>{item.source}</td><td>{item.specificGravity ?? '-'}</td><td>{item.binderSharePercent ?? item.waterSharePercent ?? '-'}</td><td>{item.materialType === 'water' ? `${item.chlorideMgL ?? '-'} mg/L` : `${item.chloridePercent ?? '-'} %`}</td><td>{item.sulfateResistanceClass ?? '-'}</td><td>{item.standardDesignation ?? '-'}</td></tr>)}</tbody></table></div></article></section></>;
}
function Field(props: { label: string; value: string; onChange: (value: string) => void }) { return <label className="field"><span>{props.label}</span><input value={props.value} onChange={event => props.onChange(event.target.value)} /></label>; }
function NumberField(props: { label: string; value: number | null; onChange: (value: number | null) => void }) { return <label className="field"><span>{props.label}</span><input type="number" value={props.value ?? ''} onChange={event => props.onChange(event.target.value === '' ? null : Number(event.target.value))} /></label>; }
