import { useMemo, useState } from 'react';
import type { DashboardProject } from './DashboardHome';

type Props = {
  projects: DashboardProject[];
  activeMixDesignId: string | null;
  onNewProject: () => void;
  onOpenProject: (mixDesignId: string) => void;
  onRefresh?: () => Promise<void>;
};
type SortKey = 'created' | 'strength' | 'name';
type ActionKind = 'duplicate' | 'archive' | 'restore' | 'status';
type ActionState = { kind: ActionKind; project: DashboardProject } | null;

function concreteTypeLabel(type: string) { if (type === 'pumped') return 'پمپی'; if (type === 'normal_weight') return 'معمولی'; return type || '-'; }
function normalizedStatus(status: string) { const value = (status || 'draft').toLowerCase(); if (value === 'trial') return 'trial_required'; if (value === 'review' || value === 'needs_review') return 'under_review'; return value; }
function statusLabel(status: string) { const value = normalizedStatus(status); const labels: Record<string,string> = { draft:'پیش‌نویس', trial_required:'Trial موردنیاز', trial_completed:'Trial تکمیل', under_review:'در بازبینی', approved:'تأییدشده', production:'تولید', superseded:'جایگزین‌شده', archived:'بایگانی' }; return labels[value] ?? value; }
function nextStatus(status: string) { const map: Record<string,string|undefined> = { draft:'trial_required', trial_required:'trial_completed', trial_completed:'under_review', under_review:'approved', approved:'production', production:'superseded' }; return map[normalizedStatus(status)]; }

export function MixDesignManager({ projects, activeMixDesignId, onNewProject, onOpenProject, onRefresh }: Props) {
  const [query, setQuery] = useState(''); const [typeFilter, setTypeFilter] = useState('all'); const [statusFilter, setStatusFilter] = useState('all'); const [sortKey, setSortKey] = useState<SortKey>('created');
  const [action, setAction] = useState<ActionState>(null); const [actorName, setActorName] = useState(''); const [duplicateName, setDuplicateName] = useState(''); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const filtered = useMemo(() => { const normalizedQuery = query.trim().toLowerCase(); const rows = projects.filter(project => { const haystack = `${project.mixDesignId} ${project.projectName} ${project.city}`.toLowerCase(); return (!normalizedQuery || haystack.includes(normalizedQuery)) && (typeFilter === 'all' || project.concreteType === typeFilter) && (statusFilter === 'all' || normalizedStatus(project.status) === statusFilter); }); return [...rows].sort((a,b) => sortKey === 'strength' ? b.targetStrengthMpa-a.targetStrengthMpa : sortKey === 'name' ? a.projectName.localeCompare(b.projectName,'fa') : String(b.createdAt).localeCompare(String(a.createdAt))); }, [projects, query, sortKey, statusFilter, typeFilter]);
  function beginAction(kind: ActionKind, project: DashboardProject) { setMessage(''); setActorName(''); setReason(''); setDuplicateName(kind === 'duplicate' ? `${project.projectName} - کپی` : ''); setAction({ kind, project }); }
  async function refreshOrReload() { if (onRefresh) await onRefresh(); else window.location.reload(); }
  async function runAction() {
    if (!action) return; setBusy(true); setMessage('');
    try {
      if (!window.tolouMixDesigns) throw new Error('API مدیریت طرح در دسترس نیست.');
      if (action.kind === 'duplicate') { const response = await window.tolouMixDesigns.duplicate({ mixDesignId: action.project.mixDesignId, projectName: duplicateName, actorName }) as { status?: string; mixDesignId?: string; error?: string }; if (response.status !== 'pass' || !response.mixDesignId) throw new Error(response.error ?? 'Duplicate ناموفق بود.'); setAction(null); setMessage('نسخه مستقل جدید با وضعیت Draft ایجاد شد. نتایج، گزارش‌ها و تاریخچه قبلی عمداً کپی نشدند.'); if (onRefresh) { await onRefresh(); onOpenProject(response.mixDesignId); } else await refreshOrReload(); return; }
      if (action.kind === 'archive') { const response = await window.tolouMixDesigns.archive(action.project.mixDesignId, actorName) as { status?: string; error?: string }; if (response.status !== 'pass') throw new Error(response.error ?? 'بایگانی ناموفق بود.'); setAction(null); setMessage('پرونده بایگانی شد و وضعیت قبلی برای Restore حفظ شد.'); await refreshOrReload(); return; }
      if (action.kind === 'restore') { const response = await window.tolouMixDesigns.restore(action.project.mixDesignId, actorName) as { status?: string; error?: string }; if (response.status !== 'pass') throw new Error(response.error ?? 'Restore ناموفق بود.'); setAction(null); setMessage('پرونده از بایگانی بازیابی شد.'); await refreshOrReload(); return; }
      const target = nextStatus(action.project.status); if (!target) throw new Error('برای وضعیت فعلی انتقال بعدی تعریف نشده است.');
      const response = await window.tolouMixDesigns.transitionStatus({ mixDesignId: action.project.mixDesignId, toStatus: target, reason, actorName }) as { status?: string; error?: string };
      if (response.status !== 'pass') throw new Error(response.error ?? 'تغییر وضعیت ناموفق بود.'); setAction(null); setMessage(`وضعیت پرونده به «${statusLabel(target)}» تغییر کرد و در Status History ثبت شد.`); await refreshOrReload();
    } catch (error) { setMessage(error instanceof Error ? error.message : 'خطای ناشناخته در عملیات مدیریتی'); } finally { setBusy(false); }
  }

  return <>
    <section className="titlebar manager-titlebar"><div><span className="eyebrow">MIX DESIGN MANAGER</span><h2>مدیریت طرح‌های اختلاط</h2><p>جستجو، فیلتر، گردش وضعیت، Duplicate و Archive پرونده‌های مهندسی</p></div><div className="toolbar"><button className="btn primary strong-action" onClick={onNewProject}>＋ ثبت طرح جدید</button></div></section>
    {message && <div className="alert info" role="status" aria-live="polite">{message}</div>}
    <section className="panel manager-filter-panel" aria-label="فیلترها و مرتب‌سازی طرح‌های اختلاط"><div className="manager-filters"><label className="manager-search"><span aria-hidden="true">⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="جستجو بر اساس کد طرح، نام پروژه یا شهر..." aria-label="جستجوی طرح اختلاط بر اساس کد، نام پروژه یا شهر" /></label><select value={typeFilter} onChange={event=>setTypeFilter(event.target.value)} aria-label="فیلتر نوع بتن"><option value="all">همه انواع بتن</option><option value="normal_weight">بتن معمولی</option><option value="pumped">بتن پمپی</option></select><select value={statusFilter} onChange={event=>setStatusFilter(event.target.value)} aria-label="فیلتر وضعیت طرح"><option value="all">همه وضعیت‌ها</option><option value="draft">پیش‌نویس</option><option value="trial_required">Trial موردنیاز</option><option value="trial_completed">Trial تکمیل</option><option value="under_review">در بازبینی</option><option value="approved">تأییدشده</option><option value="production">تولید</option><option value="superseded">جایگزین‌شده</option><option value="archived">بایگانی</option></select><select value={sortKey} onChange={event=>setSortKey(event.target.value as SortKey)} aria-label="مرتب‌سازی طرح‌های اختلاط"><option value="created">جدیدترین</option><option value="strength">بیشترین مقاومت</option><option value="name">نام پروژه</option></select></div><div className="manager-filter-summary" role="status" aria-live="polite"><b>{filtered.length}</b> طرح از {projects.length} پرونده نمایش داده می‌شود.</div></section>
    <section className="panel mix-manager-panel"><div className="panel-head"><div><h3>فهرست طرح‌های مخلوط</h3><span>هیچ تغییر وضعیت خارج از State Machine مجاز نیست.</span></div><span className="badge blue">SQLite</span></div><div className="panel-body table-wrap">{filtered.length===0?<div className="empty-state" role="status"><b>طرحی مطابق فیلتر پیدا نشد.</b><span>فیلترها را تغییر دهید یا یک طرح جدید ثبت کنید.</span></div>:<table className="mix-table manager-table"><caption className="sr-only">فهرست طرح‌های اختلاط شامل مشخصات پروژه، مقاومت هدف، وضعیت و عملیات مدیریتی</caption><thead><tr><th scope="col">کد طرح</th><th scope="col">پروژه</th><th scope="col">نوع بتن</th><th scope="col">مقاومت هدف</th><th scope="col">شهر</th><th scope="col">تاریخ</th><th scope="col">وضعیت</th><th scope="col">عملیات</th></tr></thead><tbody>{filtered.map(project=>{const archived=normalizedStatus(project.status)==='archived';const next=nextStatus(project.status);return <tr key={project.mixDesignId} className={activeMixDesignId===project.mixDesignId?'selected-row':''}><td className="mono-cell">{project.mixDesignId}</td><td><strong>{project.projectName}</strong><small>پرونده طرح اختلاط</small></td><td>{concreteTypeLabel(project.concreteType)}</td><td><strong>{project.targetStrengthMpa} MPa</strong></td><td>{project.city||'-'}</td><td>{project.createdAt||'-'}</td><td><span className={`status-chip status-${normalizedStatus(project.status)}`}>{statusLabel(project.status)}</span></td><td><div className="row-actions" aria-label={`عملیات ${project.projectName}`}><button className="row-action" onClick={()=>onOpenProject(project.mixDesignId)}>باز کردن</button>{!archived&&next&&<button className="row-action workflow" title={`انتقال به ${statusLabel(next)}`} aria-label={`انتقال ${project.projectName} به ${statusLabel(next)}`} onClick={()=>beginAction('status',project)}>مرحله بعد</button>}<button className="row-action secondary" aria-label={`ساخت نسخه مستقل از ${project.projectName}`} onClick={()=>beginAction('duplicate',project)}>Duplicate</button>{archived?<button className="row-action restore" aria-label={`بازیابی ${project.projectName} از بایگانی`} onClick={()=>beginAction('restore',project)}>Restore</button>:<button className="row-action archive" aria-label={`بایگانی ${project.projectName}`} onClick={()=>beginAction('archive',project)}>Archive</button>}</div></td></tr>})}</tbody></table>}</div></section>
    <div className="manager-roadmap-note">گردش وضعیت: <b>Draft → Trial Required → Trial Completed → Under Review → Approved → Production → Superseded</b>. برای اصلاح نسخه‌های Approved/Production باید Revision جدید ساخته شود.</div>
    {action&&<div className="management-modal-backdrop"><section className="management-modal" role="dialog" aria-modal="true" aria-labelledby="management-action-title" aria-describedby="management-action-project"><div className="panel-head"><div><h3 id="management-action-title">{action.kind==='duplicate'?'Duplicate طرح اختلاط':action.kind==='archive'?'بایگانی پرونده':action.kind==='restore'?'بازیابی پرونده':'تغییر وضعیت مهندسی'}</h3><span id="management-action-project">{action.project.projectName}</span></div><button className="modal-close" aria-label="بستن پنجره عملیات" onClick={()=>setAction(null)}>×</button></div><div className="panel-body management-action-form">{action.kind==='duplicate'&&<label><span>نام پروژه جدید</span><input value={duplicateName} onChange={event=>setDuplicateName(event.target.value)} /></label>}{action.kind==='status'&&<><div className="workflow-transition-preview" aria-label={`انتقال وضعیت از ${statusLabel(action.project.status)} به ${statusLabel(nextStatus(action.project.status)||'')}`}><span>{statusLabel(action.project.status)}</span><b aria-hidden="true">←</b><span>{statusLabel(nextStatus(action.project.status)||'')}</span></div><label><span>دلیل / توضیح انتقال وضعیت</span><textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="مثلاً Trial مطابق برنامه تکمیل شد یا طرح پس از بازبینی فنی تأیید شد" /></label></>}<label><span>نام مسئول عملیات</span><input value={actorName} onChange={event=>setActorName(event.target.value)} placeholder="برای Audit Trail" /></label><div className={`alert ${action.kind==='archive'?'warn':'info'}`}>{action.kind==='duplicate'?'طرح جدید مستقل و با وضعیت Draft ایجاد می‌شود.':action.kind==='archive'?'Snapshot نسخه جاری ذخیره و پرونده از گردش فعال خارج می‌شود.':action.kind==='restore'?'پرونده به وضعیت قبل از Archive بازمی‌گردد.':'Backend فقط انتقال بعدی مجاز در State Machine را قبول می‌کند.'}</div></div><div className="revision-form-actions"><button className="btn ghost" onClick={()=>setAction(null)}>انصراف</button><button className={`btn ${action.kind==='archive'?'danger-button':'primary'}`} disabled={busy||(action.kind==='duplicate'&&!duplicateName.trim())} onClick={()=>void runAction()}>{busy?'در حال انجام...':'تأیید عملیات'}</button></div></section></div>}
  </>;
}
