import { useEffect, useState } from 'react';

type Batch = { id: string; revisionNumber: number; batchCode: string; producedAt: string; batchQuantityM3: number; plantName?: string | null; ticketNumber?: string | null; truckNumber?: string | null; operatorName?: string | null; slumpMm?: number | null; airContentPercent?: number | null; concreteTemperatureC?: number | null; freshDensityKgM3?: number | null; };
type Detail = { batch: Batch; materials: Array<{ id: string; materialRole: string; materialName: string; targetMassKg?: number | null; batchedMassKg: number; moisturePercent?: number | null; absorptionPercent?: number | null }>; specimens: Array<{ id: string; specimenCode: string; specimenType: string; castAt: string; targetTestAgeDays?: number | null }>; strengthResults: Array<{ id: string; specimenId: string; testedAt: string; testAgeDays: number; maximumLoadKn: number; loadedAreaMm2: number; strengthMpa: number; calculationMethod: string }>; };
type Stats = { count: number; min: number | null; max: number | null; mean: number | null; populationStandardDeviation: number | null; sampleStandardDeviation: number | null; sampleCoefficientOfVariationPercent: number | null; };
type Analytics = { status: string; method: { version: string; acceptanceCriteriaApplied: boolean; passFailApplied: boolean; standardComplianceInferred: boolean }; overall: Stats; byTestAgeDays: Array<{ testAgeDays: number; statistics: Stats }>; byRevision: Array<{ revisionNumber: number; statistics: Stats }>; points: Array<{ resultId: string; specimenCode: string; batchCode: string; revisionNumber: number; testAgeDays: number; strengthMpa: number; testedAt: string }>; };

const nowLocal = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16);
const num = (value: string) => value.trim() === '' ? undefined : Number(value);
const fmt = (value: number | null | undefined) => value == null ? '—' : new Intl.NumberFormat('fa-IR', { maximumFractionDigits: 2 }).format(value);

export function ProductionQcPanel(props: { mixDesignId: string | null }) {
  const [batches, setBatches] = useState<Batch[]>([]); const [selectedId, setSelectedId] = useState(''); const [detail, setDetail] = useState<Detail | null>(null); const [analytics, setAnalytics] = useState<Analytics | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [batch, setBatch] = useState({ batchCode: '', producedAt: nowLocal(), batchQuantityM3: '1', plantName: '', ticketNumber: '', truckNumber: '', operatorName: '', slumpMm: '', airContentPercent: '', concreteTemperatureC: '', freshDensityKgM3: '' });
  const [material, setMaterial] = useState({ materialRole: 'cement', materialName: '', targetMassKg: '', batchedMassKg: '', moisturePercent: '', absorptionPercent: '' });
  const [specimen, setSpecimen] = useState({ specimenCode: '', specimenType: 'cube', castAt: nowLocal(), targetTestAgeDays: '28', widthMm: '150', heightMm: '150', lengthMm: '150', diameterMm: '' });
  const [strength, setStrength] = useState({ specimenId: '', testedAt: nowLocal(), testAgeDays: '28', maximumLoadKn: '', loadedAreaMm2: '22500', machineReference: '', failureMode: '', testedBy: '' });

  useEffect(() => { void refresh(); }, [props.mixDesignId]);
  async function refresh(selectId?: string) { if (!props.mixDesignId || !window.tolouProductionQc) { setBatches([]); setDetail(null); setAnalytics(null); return; } setError(''); try { const [listRaw, analyticsRaw] = await Promise.all([window.tolouProductionQc.listBatches(props.mixDesignId), window.tolouProductionQc.getStrengthAnalytics(props.mixDesignId)]); const list = listRaw as { status?: string; batches?: Batch[]; error?: string }; if (list.status !== 'pass') throw new Error(list.error ?? 'خواندن Production Batchها ناموفق بود.'); const rows = list.batches ?? []; setBatches(rows); const id = selectId ?? selectedId ?? rows[0]?.id ?? ''; const effective = rows.some(item => item.id === id) ? id : (rows[0]?.id ?? ''); setSelectedId(effective); if (effective) await loadDetail(effective); else setDetail(null); const a = analyticsRaw as Analytics & { error?: string }; if (a.status === 'pass') setAnalytics(a); } catch (reason) { setError(reason instanceof Error ? reason.message : 'خطا در Production/QC'); } }
  async function loadDetail(id: string) { if (!window.tolouProductionQc || !id) return; const raw = await window.tolouProductionQc.getBatch(id) as { status?: string; detail?: Detail; error?: string }; if (raw.status !== 'pass' || !raw.detail) throw new Error(raw.error ?? 'جزئیات Batch خوانده نشد.'); setDetail(raw.detail); setStrength(previous => ({ ...previous, specimenId: raw.detail?.specimens[0]?.id ?? '' })); }
  async function run(action: () => Promise<unknown>, success: string) { setBusy(true); setError(''); setMessage(''); try { const raw = await action() as { status?: string; error?: string; productionBatchId?: string }; if (raw.status !== 'pass') throw new Error(raw.error ?? 'عملیات ناموفق بود.'); setMessage(success); await refresh(raw.productionBatchId ?? selectedId); } catch (reason) { setError(reason instanceof Error ? reason.message : 'خطا در عملیات Production/QC'); } finally { setBusy(false); } }
  async function createBatch() { if (!props.mixDesignId || !window.tolouProductionQc) return; await run(() => window.tolouProductionQc!.createBatch({ mixDesignId: props.mixDesignId, batchCode: batch.batchCode, producedAt: new Date(batch.producedAt).toISOString(), batchQuantityM3: Number(batch.batchQuantityM3), plantName: batch.plantName || undefined, ticketNumber: batch.ticketNumber || undefined, truckNumber: batch.truckNumber || undefined, operatorName: batch.operatorName || undefined, slumpMm: num(batch.slumpMm), airContentPercent: num(batch.airContentPercent), concreteTemperatureC: num(batch.concreteTemperatureC), freshDensityKgM3: num(batch.freshDensityKgM3) }), 'Production Batch ثبت شد.'); }
  async function saveMaterial() { if (!selectedId || !window.tolouProductionQc) return; await run(() => window.tolouProductionQc!.saveMaterialActual({ productionBatchId: selectedId, materialRole: material.materialRole, materialName: material.materialName, targetMassKg: num(material.targetMassKg), batchedMassKg: Number(material.batchedMassKg), moisturePercent: num(material.moisturePercent), absorptionPercent: num(material.absorptionPercent) }), 'مصالح واقعی ثبت شد.'); }
  async function saveSpecimen() { if (!selectedId || !window.tolouProductionQc) return; await run(() => window.tolouProductionQc!.saveSpecimen({ productionBatchId: selectedId, specimenCode: specimen.specimenCode, specimenType: specimen.specimenType, castAt: new Date(specimen.castAt).toISOString(), targetTestAgeDays: num(specimen.targetTestAgeDays), widthMm: num(specimen.widthMm), heightMm: num(specimen.heightMm), lengthMm: num(specimen.lengthMm), diameterMm: num(specimen.diameterMm) }), 'نمونه Production ثبت شد.'); }
  async function saveStrength() { if (!strength.specimenId || !window.tolouProductionQc) return; await run(() => window.tolouProductionQc!.saveStrengthResult({ specimenId: strength.specimenId, testedAt: new Date(strength.testedAt).toISOString(), testAgeDays: Number(strength.testAgeDays), maximumLoadKn: Number(strength.maximumLoadKn), loadedAreaMm2: Number(strength.loadedAreaMm2), machineReference: strength.machineReference || undefined, failureMode: strength.failureMode || undefined, testedBy: strength.testedBy || undefined }), 'نتیجه مقاومت ثبت و MPa توسط backend محاسبه شد.'); }

  return <><section className="titlebar"><div><h2>Production / QC Workspace</h2><p>Production batches، مصالح واقعی، نمونه‌ها، مقاومت و آمار توصیفی ردیابی‌پذیر</p></div><div className="toolbar"><button className="btn" disabled={busy || !props.mixDesignId} onClick={() => void refresh()}>بروزرسانی</button></div></section>
    {error && <div className="alert danger">{error}</div>}{message && <div className="alert ok">{message}</div>}{!props.mixDesignId && <div className="alert warn">ابتدا یک Mix Design فعال انتخاب کنید.</div>}
    {props.mixDesignId && <><section className="content-grid"><article className="panel"><div className="panel-head"><div><h3>Production Batch</h3><span>ثبت فقط در وضعیت production</span></div></div><div className="panel-body form-body"><label className="field"><span>Batch code</span><input value={batch.batchCode} onChange={e => setBatch(p => ({ ...p, batchCode: e.target.value }))} /></label><label className="field"><span>Produced at</span><input type="datetime-local" value={batch.producedAt} onChange={e => setBatch(p => ({ ...p, producedAt: e.target.value }))} /></label><label className="field"><span>Volume m³</span><input type="number" min="0" step="any" value={batch.batchQuantityM3} onChange={e => setBatch(p => ({ ...p, batchQuantityM3: e.target.value }))} /></label><label className="field"><span>Plant</span><input value={batch.plantName} onChange={e => setBatch(p => ({ ...p, plantName: e.target.value }))} /></label><label className="field"><span>Ticket / Truck</span><input value={batch.ticketNumber} placeholder="Ticket" onChange={e => setBatch(p => ({ ...p, ticketNumber: e.target.value }))} /><input value={batch.truckNumber} placeholder="Truck" onChange={e => setBatch(p => ({ ...p, truckNumber: e.target.value }))} /></label><label className="field"><span>Slump / Air / Temp / Fresh density</span><input type="number" value={batch.slumpMm} placeholder="mm" onChange={e => setBatch(p => ({ ...p, slumpMm: e.target.value }))} /><input type="number" value={batch.airContentPercent} placeholder="%" onChange={e => setBatch(p => ({ ...p, airContentPercent: e.target.value }))} /><input type="number" value={batch.concreteTemperatureC} placeholder="°C" onChange={e => setBatch(p => ({ ...p, concreteTemperatureC: e.target.value }))} /><input type="number" value={batch.freshDensityKgM3} placeholder="kg/m³" onChange={e => setBatch(p => ({ ...p, freshDensityKgM3: e.target.value }))} /></label><button className="btn success" disabled={busy || !batch.batchCode.trim()} onClick={() => void createBatch()}>ثبت Batch</button></div></article>
    <article className="panel wide-panel"><div className="panel-head"><div><h3>Batch History</h3><span>Revision-bound؛ رکورد تاریخی فقط‌خواندنی</span></div><span className="badge blue">{batches.length}</span></div><div className="panel-body"><label className="field"><span>Batch</span><select value={selectedId} onChange={e => { setSelectedId(e.target.value); void loadDetail(e.target.value).catch(reason => setError(reason instanceof Error ? reason.message : String(reason))); }}><option value="">انتخاب کنید</option>{batches.map(item => <option key={item.id} value={item.id}>{item.batchCode} · R{item.revisionNumber} · {new Date(item.producedAt).toLocaleString('fa-IR')}</option>)}</select></label>{detail && <div className="table-wrap"><table><thead><tr><th>Code</th><th>Revision</th><th>Volume</th><th>Slump</th><th>Air</th><th>Temp</th><th>Density</th></tr></thead><tbody><tr><td>{detail.batch.batchCode}</td><td>R{detail.batch.revisionNumber}</td><td>{fmt(detail.batch.batchQuantityM3)}</td><td>{fmt(detail.batch.slumpMm)}</td><td>{fmt(detail.batch.airContentPercent)}</td><td>{fmt(detail.batch.concreteTemperatureC)}</td><td>{fmt(detail.batch.freshDensityKgM3)}</td></tr></tbody></table></div>}</div></article></section>
    {detail && <section className="content-grid"><article className="panel"><div className="panel-head"><div><h3>Actual Materials</h3><span>Target vs batched</span></div></div><div className="panel-body form-body"><label className="field"><span>Role</span><select value={material.materialRole} onChange={e => setMaterial(p => ({ ...p, materialRole: e.target.value }))}>{['cement','scm','water','fine_aggregate','coarse_aggregate','admixture','fiber','other'].map(v => <option key={v} value={v}>{v}</option>)}</select></label><label className="field"><span>Name</span><input value={material.materialName} onChange={e => setMaterial(p => ({ ...p, materialName: e.target.value }))} /></label><label className="field"><span>Target kg / Batched kg</span><input type="number" value={material.targetMassKg} onChange={e => setMaterial(p => ({ ...p, targetMassKg: e.target.value }))} /><input type="number" value={material.batchedMassKg} onChange={e => setMaterial(p => ({ ...p, batchedMassKg: e.target.value }))} /></label><label className="field"><span>Moisture % / Absorption %</span><input type="number" value={material.moisturePercent} onChange={e => setMaterial(p => ({ ...p, moisturePercent: e.target.value }))} /><input type="number" value={material.absorptionPercent} onChange={e => setMaterial(p => ({ ...p, absorptionPercent: e.target.value }))} /></label><button className="btn success" disabled={busy || !material.materialName || material.batchedMassKg === ''} onClick={() => void saveMaterial()}>ثبت مصالح واقعی</button><div className="standards-list">{detail.materials.map(item => <div key={item.id}>{item.materialRole} · {item.materialName}: {fmt(item.batchedMassKg)} kg</div>)}</div></div></article>
    <article className="panel"><div className="panel-head"><div><h3>Specimens</h3><span>Production specimen registry</span></div></div><div className="panel-body form-body"><label className="field"><span>Code / Type</span><input value={specimen.specimenCode} onChange={e => setSpecimen(p => ({ ...p, specimenCode: e.target.value }))} /><select value={specimen.specimenType} onChange={e => setSpecimen(p => ({ ...p, specimenType: e.target.value }))}>{['cube','cylinder','beam','other'].map(v => <option key={v}>{v}</option>)}</select></label><label className="field"><span>Cast at / Target age days</span><input type="datetime-local" value={specimen.castAt} onChange={e => setSpecimen(p => ({ ...p, castAt: e.target.value }))} /><input type="number" value={specimen.targetTestAgeDays} onChange={e => setSpecimen(p => ({ ...p, targetTestAgeDays: e.target.value }))} /></label><label className="field"><span>Width / Height / Length / Diameter mm</span><input type="number" value={specimen.widthMm} onChange={e => setSpecimen(p => ({ ...p, widthMm: e.target.value }))} /><input type="number" value={specimen.heightMm} onChange={e => setSpecimen(p => ({ ...p, heightMm: e.target.value }))} /><input type="number" value={specimen.lengthMm} onChange={e => setSpecimen(p => ({ ...p, lengthMm: e.target.value }))} /><input type="number" value={specimen.diameterMm} onChange={e => setSpecimen(p => ({ ...p, diameterMm: e.target.value }))} /></label><button className="btn success" disabled={busy || !specimen.specimenCode} onClick={() => void saveSpecimen()}>ثبت نمونه</button><div className="standards-list">{detail.specimens.map(item => <div key={item.id}>{item.specimenCode} · {item.specimenType} · {item.targetTestAgeDays ?? '—'} d</div>)}</div></div></article>
    <article className="panel"><div className="panel-head"><div><h3>Compressive Strength</h3><span>MPa محاسبه‌شده در backend</span></div></div><div className="panel-body form-body"><label className="field"><span>Specimen</span><select value={strength.specimenId} onChange={e => setStrength(p => ({ ...p, specimenId: e.target.value }))}><option value="">انتخاب کنید</option>{detail.specimens.map(item => <option key={item.id} value={item.id}>{item.specimenCode}</option>)}</select></label><label className="field"><span>Tested at / Age days</span><input type="datetime-local" value={strength.testedAt} onChange={e => setStrength(p => ({ ...p, testedAt: e.target.value }))} /><input type="number" value={strength.testAgeDays} onChange={e => setStrength(p => ({ ...p, testAgeDays: e.target.value }))} /></label><label className="field"><span>Maximum load kN / Loaded area mm²</span><input type="number" value={strength.maximumLoadKn} onChange={e => setStrength(p => ({ ...p, maximumLoadKn: e.target.value }))} /><input type="number" value={strength.loadedAreaMm2} onChange={e => setStrength(p => ({ ...p, loadedAreaMm2: e.target.value }))} /></label><button className="btn success" disabled={busy || !strength.specimenId || !strength.maximumLoadKn} onClick={() => void saveStrength()}>ثبت نتیجه مقاومت</button><div className="standards-list">{detail.strengthResults.map(item => <div key={item.id}>{item.testAgeDays} d · {fmt(item.strengthMpa)} MPa · {item.calculationMethod}</div>)}</div></div></article></section>}
    {analytics && <section className="panel form-panel"><div className="panel-head"><div><h3>Production/QC Strength Analytics</h3><span>{analytics.method.version}</span></div><span className="badge blue">n={analytics.overall.count}</span></div><div className="panel-body"><div className="result-grid"><div><label>Mean</label><strong>{fmt(analytics.overall.mean)} MPa</strong></div><div><label>Min</label><strong>{fmt(analytics.overall.min)} MPa</strong></div><div><label>Max</label><strong>{fmt(analytics.overall.max)} MPa</strong></div><div><label>Sample SD</label><strong>{fmt(analytics.overall.sampleStandardDeviation)} MPa</strong></div><div><label>Sample CV</label><strong>{fmt(analytics.overall.sampleCoefficientOfVariationPercent)} %</strong></div></div><div className="alert info">Acceptance criteria applied: خیر · Pass/Fail: خیر · Standard compliance inferred: خیر</div><div className="table-wrap"><table><thead><tr><th>Age</th><th>n</th><th>Mean MPa</th><th>SD</th><th>CV%</th></tr></thead><tbody>{analytics.byTestAgeDays.map(row => <tr key={row.testAgeDays}><td>{row.testAgeDays} d</td><td>{row.statistics.count}</td><td>{fmt(row.statistics.mean)}</td><td>{fmt(row.statistics.sampleStandardDeviation)}</td><td>{fmt(row.statistics.sampleCoefficientOfVariationPercent)}</td></tr>)}</tbody></table></div></div></section>}
    </>}</>;
}
